/*
 * RouletteConstants
 */

export const LOAD_ROULETTE = 'LOAD_ROULETTE'
export const LOAD_ROULETTE_SUCCESS = 'LOAD_ROULETTE_SUCCESS'
export const LOAD_ROULETTE_ERROR = 'LOAD_ROULETTE_ERROR'
export const LOAD_INSTANCE = 'LOAD_INSTANCE'
export const LOAD_INSTANCE_SUCCESS = 'LOAD_INSTANCE_SUCCESS'
export const LOAD_INSTANCE_ERROR = 'LOAD_INSTANCE_ERROR'
export const PLACE_BET = 'PLACE_BET'
export const ADD_BET = 'ADD_BET'
export const SET_INSTANCE = 'SET_INSTANCE'
export const SET_JACKPOT = 'SET_JACKPOT'
export const ADD_INSTANCE = 'ADD_INSTANCE'
export const INCREASE_JACKPOT = 'INCREASE_JACKPOT'
export const UPDATE_INSTANCE = 'UPDATE_INSTANCE'
export const SET_DISABLED = 'SET_DISABLED'
export const INCREMENT_SPINS = 'INCREMENT_SPINS'
export const INCREMENT_BETS = 'INCREMENT_BETS'
export const INCREMENT_SATOSHI = 'INCREMENT_SATOSHI'
